# Generated by Django 4.2.3 on 2023-07-23 01:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('Account', django.db.models.manager.Manager()),
            ],
        ),
    ]
